import React, { useState } from 'react';
import { useRouter } from 'next/router';
import { Terminal, Users, Cpu, Shield, Zap, Play, Bot, Clock, Database, Code2, Globe } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { ToastProvider, useToast } from '@/components/ui/Toast';

function LandingPageContent() {
  const router = useRouter();
  const { addToast } = useToast();
  const [isCreatingSession, setIsCreatingSession] = useState(false);

  const handleLaunch = () => {
    router.push('/auth/login');
  };

  return (
    <div className="min-h-screen bg-[#020617] text-slate-200 selection:bg-blue-500/30">
      <nav className="flex justify-between items-center p-6 max-w-7xl mx-auto border-b border-white/5">
        <div className="text-2xl font-black tracking-tighter text-white">
          iTEC<span className="text-blue-500 text-3xl">ify</span>
        </div>
        <div className="hidden md:flex gap-8 text-sm font-medium text-slate-400">
          <a href="#features" className="hover:text-white transition">Funcționalități</a>
          <a href="#sandbox" className="hover:text-white transition">Sandbox</a>
          <a href="#security" className="hover:text-white transition">Securitate</a>
        </div>
        <Button onClick={handleLaunch} isLoading={isCreatingSession}>
          Lansează App <Play size={16} />
        </Button>
      </nav>

      <header className="pt-24 pb-16 px-6 text-center max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-blue-500/30 bg-blue-500/10 text-blue-400 text-xs font-mono mb-6">
          <Zap size={14} /> iTEC 2026: Viitorul este aici
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold text-white mb-6 tracking-tight leading-tight">
          Codează la <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">viteza gândului</span> AI.
        </h1>
        <p className="text-lg text-slate-400 mb-10 leading-relaxed">
          Imaginează-ți un editor unde tu, echipa ta și agenții AI lucrați în același fișier,
          fără conflicte de Git și fără &quot;stai să fac push&quot;. Un sandbox universal pentru era post-Copilot.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button onClick={handleLaunch} size="lg" isLoading={isCreatingSession}>
            Începe un Prototip
          </Button>
          <Button variant="secondary" size="lg" onClick={() => window.open('https://github.com', '_blank')}>
            <Globe size={18} /> Vezi pe GitHub
          </Button>
        </div>
      </header>

      <section id="features" className="py-20 px-6 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="p-8 rounded-2xl bg-slate-900/50 border border-white/5 hover:border-blue-500/30 transition group">
            <Users className="text-blue-500 mb-4" size={32} />
            <h3 className="text-xl font-bold text-white mb-3">Colaborare Fluidă</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              Multi-cursor pentru toți utilizatorii și agenții AI. Prezență vizuală în stil Figma aplicată direct pe codul tău.
            </p>
            <div className="mt-4 flex items-center gap-2 text-xs text-slate-500">
              <div className="flex -space-x-2">
                <div className="w-6 h-6 rounded-full bg-blue-500 border-2 border-[#020617] flex items-center justify-center text-white text-[10px]">A</div>
                <div className="w-6 h-6 rounded-full bg-green-500 border-2 border-[#020617] flex items-center justify-center text-white text-[10px]">B</div>
                <div className="w-6 h-6 rounded-full bg-purple-500 border-2 border-[#020617] flex items-center justify-center text-white text-[10px]">🤖</div>
              </div>
              <span>3 online</span>
            </div>
          </div>

          <div className="p-8 rounded-2xl bg-slate-900/50 border border-white/5 hover:border-purple-500/30 transition">
            <Cpu className="text-purple-500 mb-4" size={32} />
            <h3 className="text-xl font-bold text-white mb-3">AI Block-Editor</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              Delimităm clar codul uman de halucinațiile AI. Blocurile generate pot fi acceptate sau refuzate cu un singur click.
            </p>
            <div className="mt-4 p-3 rounded-lg bg-purple-500/10 border border-purple-500/20">
              <div className="flex items-center gap-2 text-xs text-purple-400 mb-2">
                <Bot size={12} />
                <span>Generated by CodeBot</span>
              </div>
              <code className="text-xs text-slate-300">function optimize() {'{'}...{'}'}</code>
            </div>
          </div>

          <div className="p-8 rounded-2xl bg-slate-900/50 border border-white/5 hover:border-green-500/30 transition">
            <Shield className="text-green-500 mb-4" size={32} />
            <h3 className="text-xl font-bold text-white mb-3">Sandboxing Inteligent</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              Izolare Docker on-the-fly. Scanăm automat vulnerabilitățile înainte ca mediul tău de backend să pornească.
            </p>
            <div className="mt-4 flex items-center gap-3 text-xs">
              <span className="flex items-center gap-1 text-green-400">
                <div className="w-2 h-2 rounded-full bg-green-500" /> Node.js
              </span>
              <span className="flex items-center gap-1 text-yellow-400">
                <div className="w-2 h-2 rounded-full bg-yellow-500" /> Python
              </span>
              <span className="flex items-center gap-1 text-orange-400">
                <div className="w-2 h-2 rounded-full bg-orange-500" /> Rust
              </span>
            </div>
          </div>
        </div>
      </section>

      <section id="sandbox" className="py-20 px-6 bg-blue-600/5 border-y border-blue-500/10">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-12">
          <div className="flex-1 text-left">
            <h2 className="text-3xl font-bold text-white mb-6">Terminalul nu mai este singuratic.</h2>
            <p className="text-slate-400 mb-6 italic">
              &quot;Când cineva rulează o comandă, toți ceilalți văd output-ul.&quot;
            </p>
            <ul className="space-y-4 text-slate-300">
              <li className="flex gap-2 items-start">
                <Code2 size={18} className="text-blue-400 mt-1" />
                <span>Suport pentru Node.js, Python, Rust și multe altele.</span>
              </li>
              <li className="flex gap-2 items-start">
                <Database size={18} className="text-blue-400 mt-1" />
                <span>Limitări inteligente de CPU și memorie anti-buclă infinită.</span>
              </li>
              <li className="flex gap-2 items-start">
                <Clock size={18} className="text-blue-400 mt-1" />
                <span>Time-Travel Debugging cu snapshot-uri la fiecare 30 de secunde.</span>
              </li>
            </ul>
          </div>
          <div className="flex-1 w-full bg-[#0d1117] rounded-xl border border-slate-700 shadow-2xl overflow-hidden font-mono text-xs">
            <div className="bg-slate-800 p-2 flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div className="w-3 h-3 rounded-full bg-green-500"></div>
            </div>
            <div className="p-4 space-y-2">
              <div className="text-blue-400"># Ana scrie:</div>
              <div className="text-white">$ python3 backend_optimizer.py</div>
              <div className="text-purple-400 italic">... [AI Agent] Generating routes in real-time ...</div>
              <div className="text-green-400">✓ Server started on port 3000 (Docker Isolated)</div>
              <div className="text-slate-500">Memory used: 45MB / 512MB</div>
            </div>
          </div>
        </div>
      </section>

      <section id="security" className="py-20 px-6 max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-white mb-4">Securitate în primul rând</h2>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Fiecare linie de cod este scanată înainte de execuție. Protejăm împotriva atacurilor prin
            izolare completă în containere Docker.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-6 rounded-xl bg-slate-900/50 border border-slate-800">
            <Shield className="text-green-500 mb-4" size={24} />
            <h3 className="text-lg font-bold text-white mb-2">Scanare Automată</h3>
            <p className="text-sm text-slate-400 mb-4">
              Detectăm patterns periculoase: eval(), exec(), imports suspecte, bucle infinite.
            </p>
            <div className="space-y-2 font-mono text-xs">
              <div className="flex items-center gap-2 text-red-400">
                <span>✗</span>
                <span>eval(userInput)</span>
                <span className="text-slate-500">// blocked</span>
              </div>
              <div className="flex items-center gap-2 text-green-400">
                <span>✓</span>
                <span>console.log(message)</span>
                <span className="text-slate-500">// allowed</span>
              </div>
            </div>
          </div>
          <div className="p-6 rounded-xl bg-slate-900/50 border border-slate-800">
            <Terminal className="text-blue-500 mb-4" size={24} />
            <h3 className="text-lg font-bold text-white mb-2">Izolare Completă</h3>
            <p className="text-sm text-slate-400 mb-4">
              Containerele rulează fără acces la rețea și cu permisiuni minimale.
            </p>
            <div className="space-y-2 font-mono text-xs">
              <div className="flex items-center gap-2">
                <span className="text-slate-500">Network:</span>
                <span className="text-red-400">disabled</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-slate-500">Memory:</span>
                <span className="text-yellow-400">512MB limit</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-slate-500">Timeout:</span>
                <span className="text-yellow-400">30s max</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 px-6 text-center">
        <h2 className="text-3xl font-bold text-white mb-6">Pregătit pentru iTEC 2026?</h2>
        <Button onClick={handleLaunch} size="lg" isLoading={isCreatingSession}>
          <Play size={18} /> Începe Acum
        </Button>
      </section>

      <footer className="py-12 border-t border-white/5 text-center text-slate-500 text-sm">
        <p>© iTEC 2026. Construit pentru performanță absolută de Liga AC.</p>
        <p className="mt-2 text-xs text-slate-600">
          Next.js • CodeMirror 6 • Yjs • Docker • TypeScript
        </p>
      </footer>
    </div>
  );
}

export default function LandingPage() {
  return (
    <ToastProvider>
      <LandingPageContent />
    </ToastProvider>
  );
}
